
package mr.bpm.mbanking.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImalWSService", targetNamespace = "http://ws.mbanking.bpm.mr/", wsdlLocation = "file:/C:/Users/Bpm0318/workspace/WsMonetique/ClearingApp/src/main/java/wsdl.xml")
public class ImalWSService
    extends Service
{

    private final static URL IMALWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMALWSSERVICE_EXCEPTION;
    private final static QName IMALWSSERVICE_QNAME = new QName("http://ws.mbanking.bpm.mr/", "ImalWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Bpm0318/workspace/WsMonetique/ClearingApp/src/main/java/wsdl.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMALWSSERVICE_WSDL_LOCATION = url;
        IMALWSSERVICE_EXCEPTION = e;
    }

    public ImalWSService() {
        super(__getWsdlLocation(), IMALWSSERVICE_QNAME);
    }

    public ImalWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMALWSSERVICE_QNAME, features);
    }

    public ImalWSService(URL wsdlLocation) {
        super(wsdlLocation, IMALWSSERVICE_QNAME);
    }

    public ImalWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMALWSSERVICE_QNAME, features);
    }

    public ImalWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImalWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImalWS
     */
    @WebEndpoint(name = "ImalWSPort")
    public ImalWS getImalWSPort() {
        return super.getPort(new QName("http://ws.mbanking.bpm.mr/", "ImalWSPort"), ImalWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImalWS
     */
    @WebEndpoint(name = "ImalWSPort")
    public ImalWS getImalWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mbanking.bpm.mr/", "ImalWSPort"), ImalWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMALWSSERVICE_EXCEPTION!= null) {
            throw IMALWSSERVICE_EXCEPTION;
        }
        return IMALWSSERVICE_WSDL_LOCATION;
    }

}
