
package mr.bpm.mbanking.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImalWS", targetNamespace = "http://ws.mbanking.bpm.mr/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImalWS {


    /**
     * 
     * @return
     *     returns mr.bpm.mbanking.ws.ListImal
     * @throws ParseException_Exception
     */
    @WebMethod(operationName = "ImalOUt")
    @WebResult(name = "ImalOUt", partName = "ImalOUt")
    @Action(input = "http://ws.mbanking.bpm.mr/ImalWS/ImalOUtRequest", output = "http://ws.mbanking.bpm.mr/ImalWS/ImalOUtResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://ws.mbanking.bpm.mr/ImalWS/ImalOUt/Fault/ParseException")
    })
    public ListImal imalOUt()
        throws ParseException_Exception
    ;

}
