
package mr.bpm.mbanking.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MonetiqueWS", targetNamespace = "http://ws.mbanking.bpm.mr/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonetiqueWS {


    /**
     * 
     * @param pan
     * @return
     *     returns mr.bpm.mbanking.ws.ListMonetiqueCarte
     */
    @WebMethod
    @WebResult(name = "AuthOut", partName = "AuthOut")
    @Action(input = "http://ws.mbanking.bpm.mr/MonetiqueWS/getAuthRequest", output = "http://ws.mbanking.bpm.mr/MonetiqueWS/getAuthResponse")
    public ListMonetiqueCarte getAuth(
        @WebParam(name = "pan", partName = "pan")
        double pan);

    /**
     * 
     * @param pan
     * @return
     *     returns mr.bpm.mbanking.ws.ListMonetiqueCarte
     */
    @WebMethod
    @WebResult(name = "ClearingOut", partName = "ClearingOut")
    @Action(input = "http://ws.mbanking.bpm.mr/MonetiqueWS/getClRequest", output = "http://ws.mbanking.bpm.mr/MonetiqueWS/getClResponse")
    public ListMonetiqueCarte getCl(
        @WebParam(name = "pan", partName = "pan")
        double pan);

    /**
     * 
     * @param pan
     * @return
     *     returns mr.bpm.mbanking.ws.ListHistorique
     */
    @WebMethod
    @WebResult(name = "HistoriqueOut", partName = "HistoriqueOut")
    @Action(input = "http://ws.mbanking.bpm.mr/MonetiqueWS/getHistRequest", output = "http://ws.mbanking.bpm.mr/MonetiqueWS/getHistResponse")
    public ListHistorique getHist(
        @WebParam(name = "pan", partName = "pan")
        double pan);

    /**
     * 
     * @return
     *     returns mr.bpm.mbanking.ws.ListPan
     */
    @WebMethod
    @WebResult(name = "PanOut", partName = "PanOut")
    @Action(input = "http://ws.mbanking.bpm.mr/MonetiqueWS/getPansRequest", output = "http://ws.mbanking.bpm.mr/MonetiqueWS/getPansResponse")
    public ListPan getPans();

    /**
     * 
     * @param pan
     * @return
     *     returns mr.bpm.mbanking.ws.SoldeCarte
     */
    @WebMethod(operationName = "SoldeOut")
    @WebResult(name = "SoldeOut", partName = "SoldeOut")
    @Action(input = "http://ws.mbanking.bpm.mr/MonetiqueWS/SoldeOutRequest", output = "http://ws.mbanking.bpm.mr/MonetiqueWS/SoldeOutResponse")
    public SoldeCarte soldeOut(
        @WebParam(name = "pan", partName = "pan")
        double pan);

    /**
     * 
     * @param du
     * @param au
     * @return
     *     returns mr.bpm.mbanking.ws.ListMonetiqueCarte
     */
    @WebMethod(operationName = "SoldeSSOut")
    @WebResult(name = "SlSSOut", partName = "SlSSOut")
    @Action(input = "http://ws.mbanking.bpm.mr/MonetiqueWS/SoldeSSOutRequest", output = "http://ws.mbanking.bpm.mr/MonetiqueWS/SoldeSSOutResponse")
    public ListMonetiqueCarte soldeSSOut(
        @WebParam(name = "du", partName = "du")
        XMLGregorianCalendar du,
        @WebParam(name = "au", partName = "au")
        XMLGregorianCalendar au);

}
