
package mr.bpm.mbanking.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MonetiqueWSService", targetNamespace = "http://ws.mbanking.bpm.mr/", wsdlLocation = "file:/C:/Users/Bpm0318/workspace/WsMonetique/ClearingApp/src/main/java/wsdl.xml")
public class MonetiqueWSService
    extends Service
{

    private final static URL MONETIQUEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MONETIQUEWSSERVICE_EXCEPTION;
    private final static QName MONETIQUEWSSERVICE_QNAME = new QName("http://ws.mbanking.bpm.mr/", "MonetiqueWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Bpm0318/workspace/WsMonetique/ClearingApp/src/main/java/wsdl.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONETIQUEWSSERVICE_WSDL_LOCATION = url;
        MONETIQUEWSSERVICE_EXCEPTION = e;
    }

    public MonetiqueWSService() {
        super(__getWsdlLocation(), MONETIQUEWSSERVICE_QNAME);
    }

    public MonetiqueWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONETIQUEWSSERVICE_QNAME, features);
    }

    public MonetiqueWSService(URL wsdlLocation) {
        super(wsdlLocation, MONETIQUEWSSERVICE_QNAME);
    }

    public MonetiqueWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONETIQUEWSSERVICE_QNAME, features);
    }

    public MonetiqueWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonetiqueWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MonetiqueWS
     */
    @WebEndpoint(name = "MonetiqueWSPort")
    public MonetiqueWS getMonetiqueWSPort() {
        return super.getPort(new QName("http://ws.mbanking.bpm.mr/", "MonetiqueWSPort"), MonetiqueWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonetiqueWS
     */
    @WebEndpoint(name = "MonetiqueWSPort")
    public MonetiqueWS getMonetiqueWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mbanking.bpm.mr/", "MonetiqueWSPort"), MonetiqueWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONETIQUEWSSERVICE_EXCEPTION!= null) {
            throw MONETIQUEWSSERVICE_EXCEPTION;
        }
        return MONETIQUEWSSERVICE_WSDL_LOCATION;
    }

}
